name: Publish Wiki

on:
  push:
    paths:
      - .github/wiki/**
    branches:
      - master

jobs:
  publish:
    name: Publish Wiki
    uses: nimblehq/github-actions-workflows/.github/workflows/publish_wiki.yml@0.1.0
    with:
      USER_NAME: github-wiki-workflow
      USER_EMAIL: ${{ secrets.GH_EMAIL }}
    secrets:
      USER_TOKEN: ${{ secrets.GH_ACTION_TOKEN }}
